"""Generate orchestration customization surfaces from canonical shared skills."""

from __future__ import annotations

import argparse
import hashlib
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from scripts.dev_tools.generate_codex_agent_variants import CODEX_WRAPPER_LINES

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR_PATH = "scripts/dev_tools/generate_orchestration_customization_surfaces.py"
GENERATED_MARKER = f"Generated by {GENERATOR_PATH}."

REVIEWER_SOURCES = (
    Path(".agents/skills/feature-review/SKILL.md"),
    Path(".agents/skills/feature-review-workflow/SKILL.md"),
    Path(".agents/skills/remediation-handoff-atomic-planner/SKILL.md"),
)
ORCHESTRATOR_SOURCES = (
    Path(".agents/skills/orchestrate/SKILL.md"),
    Path(".agents/skills/orchestrator-workflow/SKILL.md"),
)

SurfaceFamily = Literal["reviewer", "orchestrator", "researcher"]
_FamilyMap = dict[str, SurfaceFamily]
_HANDOFF = "Delegate permitted remediation planning through the canonical contract."
_AUDIT = "Review a feature branch and emit deterministic audit and remediation results."
_ORCHESTRATION = "Coordinate deterministic repository orchestration and remediation."
_ORCH_RULE = "Enforce canonical orchestration and remediation state transitions."


@dataclass(frozen=True)
class Surface:
    """Describe one generated customization surface."""

    path: Path
    family: SurfaceFamily
    kind: str
    name: str
    description: str
    prompt_agent: str | None = None


def _declared_surface(row: str) -> Surface:
    """Parse one validated compact inventory row without changing its order."""
    fields = row.split("|")
    family_code, path, kind, name, prompt_agent = fields
    if family_code not in _FAMILY_CODES:
        raise ValueError(f"Unknown surface family code: {family_code!r}")
    family = _FAMILY_CODES[family_code]
    if family == "reviewer":
        description = (
            _HANDOFF
            if name == "remediation-handoff-atomic-planner"
            else {
                "prompt": "Run the canonical feature-review workflow.",
                "skill": "Execute the canonical feature-review workflow.",
            }.get(kind, _AUDIT)
        )
    elif family == "orchestrator":
        if kind == "prompt":
            scope = {
                "orchestrate-work": "repository",
                "orchestrate-python-work": "Python",
                "orchestrate-powershell-work": "PowerShell",
                "orchestrate-csharp-work": "C#",
            }[name]
            description = f"Run deterministic {scope} orchestration."
        else:
            description = {
                "github-agent": _ORCHESTRATION,
                "claude-agent": _ORCHESTRATION,
                "skill": (
                    "Route work through deterministic orchestration and remediation."
                ),
                "rule": _ORCH_RULE,
            }[kind]
    elif kind in {"prompt", "skill"}:
        description = "Research an issue within the orchestrator-supplied tracked root."
    else:
        description = (
            "Research within the exact tracked root supplied by the orchestrator."
        )
    return Surface(Path(path), family, kind, name, description, prompt_agent)


_FAMILY_CODES: _FamilyMap = {"r": "reviewer", "o": "orchestrator", "q": "researcher"}
_SURFACE_ROWS = """\
r|.codex/agents/feature-review.toml|codex-agent|feature-review|
r|.github/agents/feature-review.agent.md|github-agent|feature_code_review_agent|
r|.github/prompts/review-feature.prompt.md|prompt|review-feature|feature_code_review_agent
r|.github/skills/feature-review-workflow/SKILL.md|skill|feature-review-workflow|
r|.github/skills/remediation-handoff-atomic-planner/SKILL.md|skill|remediation-handoff-atomic-planner|
r|.claude/agents/feature-review.md|claude-agent|feature-review|
r|.claude/skills/feature-review-workflow/SKILL.md|skill|feature-review-workflow|
r|.claude/skills/remediation-handoff-atomic-planner/SKILL.md|skill|remediation-handoff-atomic-planner|
o|.github/agents/orchestrator.agent.md|github-agent|orchestrator|
q|.github/agents/task-researcher.agent.md|github-agent|Task Researcher Instructions|
o|.github/prompts/orchestrate-work.prompt.md|prompt|orchestrate-work|orchestrator
o|.github/prompts/orchestrate-python-work.prompt.md|prompt|orchestrate-python-work|python-orchestrator
o|.github/prompts/orchestrate-powershell-work.prompt.md|prompt|orchestrate-powershell-work|powershell-orchestrator
o|.github/prompts/orchestrate-csharp-work.prompt.md|prompt|orchestrate-csharp-work|csharp-orchestrator
q|.github/prompts/research-issue.prompt.md|prompt|research-issue|Task Researcher\
 Instructions
o|.claude/agents/orchestrator.md|claude-agent|orchestrator|
q|.claude/agents/task-researcher.md|claude-agent|task-researcher|
o|.claude/skills/orchestrate/SKILL.md|skill|orchestrate|
q|.claude/skills/research-issue/SKILL.md|skill|research-issue|
o|.claude/rules/orchestrator-state.md|rule|orchestrator-state|
""".splitlines()
SURFACES = tuple(_declared_surface(row) for row in _SURFACE_ROWS)
_DIRECT_COMMANDS = (
    "drmCopilotExtension.newPotentialEntry",
    "drmCopilotExtension.newPotentialBugEntry",
    "drmCopilotExtension.potentialToIssue",
    "drmCopilotExtension.newActiveFeatureFolder",
)
_RECEIPT_KEYS = (
    "delegation_receipts.promotion.potential_entry",
    "delegation_receipts.promotion.issue",
    "delegation_receipts.promotion.feature_folder",
)


def read_source(path: Path) -> str:
    """Read one required canonical source with normalized line endings."""
    absolute_path = REPO_ROOT / path
    if not absolute_path.is_file():
        raise FileNotFoundError(f"Canonical source is missing: {path.as_posix()}")
    return (
        absolute_path.read_text(encoding="utf-8").replace("\r\n", "\n").rstrip() + "\n"
    )


def _strip_frontmatter(text: str) -> str:
    """Return a Markdown document body without YAML frontmatter."""
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        return text.strip()
    try:
        closing_index = lines.index("---", 1)
    except ValueError as error:
        raise ValueError(
            "Canonical Markdown source has unterminated frontmatter."
        ) from error
    return "\n".join(lines[closing_index + 1 :]).strip()


def _section(text: str, start: str, end: str) -> str:
    """Extract one exact canonical Markdown section."""
    start_index = text.find(start)
    end_index = text.find(end, start_index + len(start))
    if start_index < 0 or end_index < 0:
        raise ValueError(f"Canonical section boundary is missing: {start!r} -> {end!r}")
    return text[start_index:end_index].strip()


def _provenance(sources: tuple[Path, ...], texts: dict[Path, str]) -> str:
    """Render source paths and digests so every source drives every target."""
    rows = [GENERATED_MARKER, "Canonical inputs:"]
    for source in sources:
        digest = hashlib.sha256(texts[source].encode("utf-8")).hexdigest()
        rows.append(f"- `{source.as_posix()}` (`sha256:{digest}`)")
    return "\n".join(rows)


def _reviewer_payload(texts: dict[Path, str]) -> str:
    """Compose the complete reviewer contract from all canonical inputs."""
    sections: list[str] = []
    for source in REVIEWER_SOURCES:
        sections.extend(
            (
                f"## Canonical source: `{source.as_posix()}`",
                _strip_frontmatter(texts[source]),
            )
        )
    return "\n\n".join(sections)


def _orchestrator_payload(texts: dict[Path, str]) -> str:
    """Compose the generated orchestration contract from canonical sections."""
    orchestrate = texts[ORCHESTRATOR_SOURCES[0]]
    workflow = texts[ORCHESTRATOR_SOURCES[1]]
    return "\n\n".join(
        (
            _section(orchestrate, "## Delegation Model", "## Completion Requirements"),
            _section(
                orchestrate,
                "## Post-Review Outcome Evaluation",
                "## Release-Boundary Validator Parity",
            ),
            _section(
                workflow,
                "## Deterministic Handoff Result Contract",
                "## Resume Rules",
            ),
            _section(workflow, "## Shared Remediation Loop", "## Completion Gates"),
        )
    )


def _host_compatibility(surface: Surface) -> str:
    """Return compatibility text owned only by the selected host projection."""
    if surface.path == Path(".codex/agents/feature-review.toml"):
        return "\n".join(
            (
                "Canonical migration source: .github/agents/feature-review.agent.md",
                *CODEX_WRAPPER_LINES,
            )
        )
    if surface.path == Path(".github/agents/orchestrator.agent.md"):
        feature_entry, bug_entry, to_issue, active_folder = _DIRECT_COMMANDS
        modes = "`minor-audit`, `full-feature`, or `full-bug`"
        return "\n".join(
            (
                "## Direct GitHub Host Lifecycle Contract",
                "",
                f"- Use `{feature_entry}` for features and `{bug_entry}` for bugs.",
                f"- Use `{to_issue}` with explicit work mode {modes}.",
                f"- Use `{active_folder}` with `--issue-number`, the numeric "
                "issue number, and the explicit selected work mode.",
            )
        )
    if surface.path == Path(".claude/agents/orchestrator.md"):
        return "\n".join(
            (
                "## Claude Promotion Receipt Namespace",
                "",
                "- `delegation_receipts.promotion.potential_entry`",
                "- `delegation_receipts.promotion.issue`",
                "- `delegation_receipts.promotion.feature_folder`",
            )
        )
    if surface.family == "orchestrator" and surface.kind == "prompt":
        return "\n".join(
            (
                "## Small Path Compatibility",
                "",
                "- Use `minor-audit` and require an explicit `## Acceptance "
                "Criteria` section in `issue.md`.",
                "- Require `DIRECTIVE: MINIMAL-AUDIT PLAN REQUIRED` and "
                "`PREFLIGHT: ALL CLEAR`.",
                "- Execute `Phase 0 only`, then continue automated "
                "implementation and validation against issue.md.",
            )
        )
    return ""


def _project_payload(surface: Surface, payload: str) -> str:
    """Append only the compatibility text authorized for this host surface."""
    compatibility = _host_compatibility(surface)
    return f"{payload}\n\n{compatibility}" if compatibility else payload


def _researcher_payload(texts: dict[Path, str]) -> str:
    """Compose the exact tracked-research-root contract."""
    orchestrate = texts[ORCHESTRATOR_SOURCES[0]]
    delegation = _section(
        orchestrate, "## Delegation Model", "## Evidence Location Authority"
    )
    evidence = _section(
        orchestrate, "## Evidence Location Authority", "## Completion Requirements"
    )
    return "\n\n".join((delegation, evidence))


def _yaml_frontmatter(surface: Surface) -> str:
    """Render host-appropriate deterministic YAML frontmatter."""
    if surface.kind == "prompt":
        return (
            "---\n"
            f"agent: '{surface.prompt_agent}'\n"
            f"description: '{surface.description}'\n"
            "---"
        )
    lines = ["---", f"name: {surface.name}", f"description: '{surface.description}'"]
    if surface.kind == "github-agent":
        lines.append(
            "tools: [execute, read, agent, edit, search, web, "
            "'drmcopilotextension/*', todo]"
        )
    elif surface.kind == "claude-agent":
        lines.extend(
            (
                "model: sonnet",
                "tools:",
                "  - Read",
                "  - Grep",
                "  - Glob",
                "  - Write",
                "  - Edit",
                "  - Agent",
            )
        )
    lines.append("---")
    return "\n".join(lines)


def _render_markdown(surface: Surface, provenance: str, payload: str) -> str:
    """Render one generated Markdown customization surface."""
    title = surface.name.replace("-", " ").title()
    marker = "<!--\n" + provenance + "\n-->"
    if surface.kind == "rule":
        return f"{marker}\n\n# {title}\n\n{payload}\n"
    return f"{_yaml_frontmatter(surface)}\n\n{marker}\n\n# {title}\n\n{payload}\n"


def _render_codex_agent(surface: Surface, provenance: str, payload: str) -> str:
    """Render the generated Codex feature-review agent."""
    if "'''" in payload:
        raise ValueError(
            "Canonical reviewer content cannot contain TOML triple-single quotes."
        )
    comments = "\n".join(f"# {line}" for line in provenance.splitlines())
    return (
        f"{comments}\n"
        f'name = "{surface.name}"\n'
        f'description = "{surface.description}"\n'
        "developer_instructions = '''\n"
        f"{payload}\n"
        "'''\n"
    )


def expected_outputs() -> dict[Path, str]:
    """Return the exact generated output for every declared target."""
    source_paths = REVIEWER_SOURCES + ORCHESTRATOR_SOURCES
    texts = {path: read_source(path) for path in source_paths}
    payloads = {
        "reviewer": _reviewer_payload(texts),
        "orchestrator": _orchestrator_payload(texts),
        "researcher": _researcher_payload(texts),
    }
    provenances = {
        "reviewer": _provenance(REVIEWER_SOURCES, texts),
        "orchestrator": _provenance(ORCHESTRATOR_SOURCES, texts),
        "researcher": _provenance(ORCHESTRATOR_SOURCES, texts),
    }
    outputs: dict[Path, str] = {}
    for surface in SURFACES:
        payload = _project_payload(surface, payloads[surface.family])
        provenance = provenances[surface.family]
        if surface.kind == "codex-agent":
            outputs[surface.path] = _render_codex_agent(surface, provenance, payload)
        else:
            outputs[surface.path] = _render_markdown(surface, provenance, payload)
    validate_outputs(outputs)
    return outputs


def validate_outputs(outputs: dict[Path, str]) -> None:
    """Fail closed if generated content weakens the canonical contracts."""
    expected_paths = {surface.path for surface in SURFACES}
    if set(outputs) != expected_paths:
        raise ValueError(
            "Generated output paths do not match the declared exact target set."
        )
    for surface in SURFACES:
        text = outputs[surface.path]
        github_agent = surface.path == Path(".github/agents/orchestrator.agent.md")
        claude_agent = surface.path == Path(".claude/agents/orchestrator.md")
        if github_agent != all(token in text for token in _DIRECT_COMMANDS):
            raise ValueError(f"GitHub host identifiers crossed {surface.path}.")
        if claude_agent != all(token in text for token in _RECEIPT_KEYS):
            raise ValueError(f"Claude receipt identifiers crossed {surface.path}.")
        if surface.family == "orchestrator" and surface.kind == "prompt":
            for token in (
                "minor-audit",
                "explicit `## Acceptance Criteria` section",
                "DIRECTIVE: MINIMAL-AUDIT PLAN REQUIRED",
                "PREFLIGHT: ALL CLEAR",
                "Phase 0 only",
                "validation against issue.md",
            ):
                if token not in text:
                    raise ValueError(
                        f"Prompt token {token!r} missing from {surface.path}."
                    )
        if "REVIEW_STATUS:" in text:
            raise ValueError(
                f"Binary-only review status remains in {surface.path.as_posix()}."
            )
        if surface.family == "reviewer":
            for token in (
                "REVIEW_VERDICT: PASS | BLOCKED",
                "REMEDIATION_ACTION: NONE | AUTONOMOUS",
                "BLOCKER_FINGERPRINT: NONE | sha256:<64-lowercase-hex>",
                "Only `BLOCKED` plus `AUTONOMOUS`",
                "no actionable repository candidate",
            ):
                if token not in text:
                    raise ValueError(
                        f"Reviewer token {token!r} missing from {surface.path}."
                    )
        elif surface.family == "orchestrator":
            for token in (
                "Canonical Post-R4 Fingerprint and Exception Gate",
                "one exact unused exception",
                "atomically set `consumed_at`",
                "can never authorize another transition",
                "blocked_remediation_loop_limit",
                "`blocked_cycle_limit` is rejected legacy input",
                "Only `REVIEW_VERDICT: BLOCKED` plus `REMEDIATION_ACTION: AUTONOMOUS`",
            ):
                if token not in text:
                    raise ValueError(
                        f"Orchestrator token {token!r} missing from {surface.path}."
                    )
        else:
            for token in ("<feature-folder>/research/", "docs/research/"):
                if token not in text:
                    raise ValueError(
                        f"Research root token {token!r} missing from {surface.path}."
                    )


def find_extra_generated_targets(expected_paths: set[Path]) -> list[Path]:
    """Find marked generated files outside the exact target set."""
    roots = (Path(".codex/agents"), Path(".github"), Path(".claude"))
    extras: list[Path] = []
    for root in roots:
        for path in sorted((REPO_ROOT / root).rglob("*")):
            if not path.is_file() or path.suffix not in {".md", ".toml"}:
                continue
            relative_path = path.relative_to(REPO_ROOT)
            if relative_path in expected_paths:
                continue
            contents = path.read_text(encoding="utf-8", errors="replace")
            if GENERATED_MARKER in contents.partition("developer_instructions")[0]:
                extras.append(relative_path)
    return extras


def synchronize(*, check: bool) -> list[str]:
    """Write or verify every declared surface and reject extra generated files."""
    outputs = expected_outputs()
    errors: list[str] = []
    for path, expected in outputs.items():
        absolute_path = REPO_ROOT / path
        actual = (
            absolute_path.read_text(encoding="utf-8")
            if absolute_path.is_file()
            else None
        )
        if check:
            if actual is None:
                errors.append(
                    f"Generated orchestration surface is missing: {path.as_posix()}"
                )
            elif actual != expected:
                errors.append(
                    f"Generated orchestration surface is stale: {path.as_posix()}"
                )
        elif actual != expected:
            absolute_path.parent.mkdir(parents=True, exist_ok=True)
            absolute_path.write_text(expected, encoding="utf-8", newline="\n")
            print(f"UPDATED {path.as_posix()}")
    for extra in find_extra_generated_targets(set(outputs)):
        errors.append(f"Unexpected generated orchestration surface: {extra.as_posix()}")
    if not errors:
        print(f"VERIFIED {len(outputs)} orchestration customization surfaces")
    return errors


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report generated-surface drift without writing.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """Generate or check the exact orchestration customization surfaces."""
    args = build_parser().parse_args(argv)
    try:
        errors = synchronize(check=bool(args.check))
    except (FileNotFoundError, OSError, ValueError) as error:
        print(str(error), file=sys.stderr)
        return 1
    for error in errors:
        print(error, file=sys.stderr)
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
