"""Generate orchestration customization surfaces from canonical shared skills."""

from __future__ import annotations

import argparse
import hashlib
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR_PATH = "scripts/dev_tools/generate_orchestration_customization_surfaces.py"
GENERATED_MARKER = f"Generated by {GENERATOR_PATH}."

REVIEWER_SOURCES = (
    Path(".agents/skills/feature-review/SKILL.md"),
    Path(".agents/skills/feature-review-workflow/SKILL.md"),
    Path(".agents/skills/remediation-handoff-atomic-planner/SKILL.md"),
)
ORCHESTRATOR_SOURCES = (
    Path(".agents/skills/orchestrate/SKILL.md"),
    Path(".agents/skills/orchestrator-workflow/SKILL.md"),
)

SurfaceFamily = Literal["reviewer", "orchestrator", "researcher"]


@dataclass(frozen=True)
class Surface:
    """Describe one generated customization surface."""

    path: Path
    family: SurfaceFamily
    kind: str
    name: str
    description: str
    prompt_agent: str | None = None


SURFACES = (
    Surface(
        Path(".codex/agents/feature-review.toml"),
        "reviewer",
        "codex-agent",
        "feature-review",
        "Review a feature branch and emit deterministic audit and remediation results.",
    ),
    Surface(
        Path(".github/agents/feature-review.agent.md"),
        "reviewer",
        "github-agent",
        "feature_code_review_agent",
        "Review a feature branch and emit deterministic audit and remediation results.",
    ),
    Surface(
        Path(".github/prompts/review-feature.prompt.md"),
        "reviewer",
        "prompt",
        "review-feature",
        "Run the canonical feature-review workflow.",
        "feature_code_review_agent",
    ),
    Surface(
        Path(".github/skills/feature-review-workflow/SKILL.md"),
        "reviewer",
        "skill",
        "feature-review-workflow",
        "Execute the canonical feature-review workflow.",
    ),
    Surface(
        Path(".github/skills/remediation-handoff-atomic-planner/SKILL.md"),
        "reviewer",
        "skill",
        "remediation-handoff-atomic-planner",
        "Delegate permitted remediation planning through the canonical contract.",
    ),
    Surface(
        Path(".claude/agents/feature-review.md"),
        "reviewer",
        "claude-agent",
        "feature-review",
        "Review a feature branch and emit deterministic audit and remediation results.",
    ),
    Surface(
        Path(".claude/skills/feature-review-workflow/SKILL.md"),
        "reviewer",
        "skill",
        "feature-review-workflow",
        "Execute the canonical feature-review workflow.",
    ),
    Surface(
        Path(".claude/skills/remediation-handoff-atomic-planner/SKILL.md"),
        "reviewer",
        "skill",
        "remediation-handoff-atomic-planner",
        "Delegate permitted remediation planning through the canonical contract.",
    ),
    Surface(
        Path(".github/agents/orchestrator.agent.md"),
        "orchestrator",
        "github-agent",
        "orchestrator",
        "Coordinate deterministic repository orchestration and remediation.",
    ),
    Surface(
        Path(".github/agents/task-researcher.agent.md"),
        "researcher",
        "github-agent",
        "Task Researcher Instructions",
        "Research within the exact tracked root supplied by the orchestrator.",
    ),
    Surface(
        Path(".github/prompts/orchestrate-work.prompt.md"),
        "orchestrator",
        "prompt",
        "orchestrate-work",
        "Run deterministic repository orchestration.",
        "orchestrator",
    ),
    Surface(
        Path(".github/prompts/orchestrate-python-work.prompt.md"),
        "orchestrator",
        "prompt",
        "orchestrate-python-work",
        "Run deterministic Python orchestration.",
        "python-orchestrator",
    ),
    Surface(
        Path(".github/prompts/orchestrate-powershell-work.prompt.md"),
        "orchestrator",
        "prompt",
        "orchestrate-powershell-work",
        "Run deterministic PowerShell orchestration.",
        "powershell-orchestrator",
    ),
    Surface(
        Path(".github/prompts/orchestrate-csharp-work.prompt.md"),
        "orchestrator",
        "prompt",
        "orchestrate-csharp-work",
        "Run deterministic C# orchestration.",
        "csharp-orchestrator",
    ),
    Surface(
        Path(".github/prompts/research-issue.prompt.md"),
        "researcher",
        "prompt",
        "research-issue",
        "Research an issue within the orchestrator-supplied tracked root.",
        "Task Researcher Instructions",
    ),
    Surface(
        Path(".claude/agents/orchestrator.md"),
        "orchestrator",
        "claude-agent",
        "orchestrator",
        "Coordinate deterministic repository orchestration and remediation.",
    ),
    Surface(
        Path(".claude/agents/task-researcher.md"),
        "researcher",
        "claude-agent",
        "task-researcher",
        "Research within the exact tracked root supplied by the orchestrator.",
    ),
    Surface(
        Path(".claude/skills/orchestrate/SKILL.md"),
        "orchestrator",
        "skill",
        "orchestrate",
        "Route work through deterministic orchestration and remediation.",
    ),
    Surface(
        Path(".claude/skills/research-issue/SKILL.md"),
        "researcher",
        "skill",
        "research-issue",
        "Research an issue within the orchestrator-supplied tracked root.",
    ),
    Surface(
        Path(".claude/rules/orchestrator-state.md"),
        "orchestrator",
        "rule",
        "orchestrator-state",
        "Enforce canonical orchestration and remediation state transitions.",
    ),
)


def read_source(path: Path) -> str:
    """Read one required canonical source with normalized line endings."""

    absolute_path = REPO_ROOT / path
    if not absolute_path.is_file():
        raise FileNotFoundError(f"Canonical source is missing: {path.as_posix()}")
    return (
        absolute_path.read_text(encoding="utf-8").replace("\r\n", "\n").rstrip() + "\n"
    )


def _strip_frontmatter(text: str) -> str:
    """Return a Markdown document body without YAML frontmatter."""

    lines = text.splitlines()
    if not lines or lines[0] != "---":
        return text.strip()
    try:
        closing_index = lines.index("---", 1)
    except ValueError as error:
        raise ValueError(
            "Canonical Markdown source has unterminated frontmatter."
        ) from error
    return "\n".join(lines[closing_index + 1 :]).strip()


def _section(text: str, start: str, end: str) -> str:
    """Extract one exact canonical Markdown section."""

    start_index = text.find(start)
    end_index = text.find(end, start_index + len(start))
    if start_index < 0 or end_index < 0:
        raise ValueError(f"Canonical section boundary is missing: {start!r} -> {end!r}")
    return text[start_index:end_index].strip()


def _provenance(sources: tuple[Path, ...], texts: dict[Path, str]) -> str:
    """Render source paths and digests so every source drives every target."""

    rows = [GENERATED_MARKER, "Canonical inputs:"]
    for source in sources:
        digest = hashlib.sha256(texts[source].encode("utf-8")).hexdigest()
        rows.append(f"- `{source.as_posix()}` (`sha256:{digest}`)")
    return "\n".join(rows)


def _reviewer_payload(texts: dict[Path, str]) -> str:
    """Compose the complete reviewer contract from all canonical inputs."""

    sections: list[str] = []
    for source in REVIEWER_SOURCES:
        sections.extend(
            (
                f"## Canonical source: `{source.as_posix()}`",
                _strip_frontmatter(texts[source]),
            )
        )
    return "\n\n".join(sections)


def _orchestrator_payload(texts: dict[Path, str]) -> str:
    """Compose the generated orchestration contract from canonical sections."""

    orchestrate = texts[ORCHESTRATOR_SOURCES[0]]
    workflow = texts[ORCHESTRATOR_SOURCES[1]]
    return "\n\n".join(
        (
            _section(orchestrate, "## Delegation Model", "## Completion Requirements"),
            _section(
                orchestrate,
                "## Post-Review Outcome Evaluation",
                "## Release-Boundary Validator Parity",
            ),
            _section(
                workflow,
                "## Deterministic Handoff Result Contract",
                "## Resume Rules",
            ),
            _section(workflow, "## Shared Remediation Loop", "## Completion Gates"),
        )
    )


def _researcher_payload(texts: dict[Path, str]) -> str:
    """Compose the exact tracked-research-root contract."""

    orchestrate = texts[ORCHESTRATOR_SOURCES[0]]
    delegation = _section(
        orchestrate, "## Delegation Model", "## Evidence Location Authority"
    )
    evidence = _section(
        orchestrate, "## Evidence Location Authority", "## Completion Requirements"
    )
    return "\n\n".join((delegation, evidence))


def _yaml_frontmatter(surface: Surface) -> str:
    """Render host-appropriate deterministic YAML frontmatter."""

    if surface.kind == "prompt":
        return (
            "---\n"
            f"agent: '{surface.prompt_agent}'\n"
            f"description: '{surface.description}'\n"
            "---"
        )
    lines = ["---", f"name: {surface.name}", f"description: '{surface.description}'"]
    if surface.kind == "github-agent":
        lines.append(
            "tools: [execute, read, agent, edit, search, web, "
            "'drmcopilotextension/*', todo]"
        )
    elif surface.kind == "claude-agent":
        lines.extend(
            (
                "model: sonnet",
                "tools:",
                "  - Read",
                "  - Grep",
                "  - Glob",
                "  - Write",
                "  - Edit",
                "  - Agent",
            )
        )
    lines.append("---")
    return "\n".join(lines)


def _render_markdown(surface: Surface, provenance: str, payload: str) -> str:
    """Render one generated Markdown customization surface."""

    title = surface.name.replace("-", " ").title()
    marker = "<!--\n" + provenance + "\n-->"
    if surface.kind == "rule":
        return f"{marker}\n\n# {title}\n\n{payload}\n"
    return f"{_yaml_frontmatter(surface)}\n\n{marker}\n\n# {title}\n\n{payload}\n"


def _render_codex_agent(surface: Surface, provenance: str, payload: str) -> str:
    """Render the generated Codex feature-review agent."""

    if "'''" in payload:
        raise ValueError(
            "Canonical reviewer content cannot contain TOML triple-single quotes."
        )
    comments = "\n".join(f"# {line}" for line in provenance.splitlines())
    return (
        f"{comments}\n"
        f'name = "{surface.name}"\n'
        f'description = "{surface.description}"\n'
        "developer_instructions = '''\n"
        f"{payload}\n"
        "'''\n"
    )


def expected_outputs() -> dict[Path, str]:
    """Return the exact generated output for every declared target."""

    source_paths = REVIEWER_SOURCES + ORCHESTRATOR_SOURCES
    texts = {path: read_source(path) for path in source_paths}
    payloads = {
        "reviewer": _reviewer_payload(texts),
        "orchestrator": _orchestrator_payload(texts),
        "researcher": _researcher_payload(texts),
    }
    provenances = {
        "reviewer": _provenance(REVIEWER_SOURCES, texts),
        "orchestrator": _provenance(ORCHESTRATOR_SOURCES, texts),
        "researcher": _provenance(ORCHESTRATOR_SOURCES, texts),
    }
    outputs: dict[Path, str] = {}
    for surface in SURFACES:
        payload = payloads[surface.family]
        provenance = provenances[surface.family]
        if surface.kind == "codex-agent":
            outputs[surface.path] = _render_codex_agent(surface, provenance, payload)
        else:
            outputs[surface.path] = _render_markdown(surface, provenance, payload)
    validate_outputs(outputs)
    return outputs


def validate_outputs(outputs: dict[Path, str]) -> None:
    """Fail closed if generated content weakens the canonical contracts."""

    expected_paths = {surface.path for surface in SURFACES}
    if set(outputs) != expected_paths:
        raise ValueError(
            "Generated output paths do not match the declared exact target set."
        )
    for surface in SURFACES:
        text = outputs[surface.path]
        if "REVIEW_STATUS:" in text:
            raise ValueError(
                f"Binary-only review status remains in {surface.path.as_posix()}."
            )
        if surface.family == "reviewer":
            for token in (
                "REVIEW_VERDICT: PASS | BLOCKED",
                "REMEDIATION_ACTION: NONE | AUTONOMOUS",
                "BLOCKER_FINGERPRINT: NONE | sha256:<64-lowercase-hex>",
                "Only `BLOCKED` plus `AUTONOMOUS`",
                "no actionable repository candidate",
            ):
                if token not in text:
                    raise ValueError(
                        f"Reviewer token {token!r} missing from {surface.path}."
                    )
        elif surface.family == "orchestrator":
            for token in (
                "Canonical Post-R4 Fingerprint and Exception Gate",
                "one exact unused exception",
                "atomically set `consumed_at`",
                "can never authorize another transition",
                "blocked_remediation_loop_limit",
                "`blocked_cycle_limit` is rejected legacy input",
                "Only `REVIEW_VERDICT: BLOCKED` plus `REMEDIATION_ACTION: AUTONOMOUS`",
            ):
                if token not in text:
                    raise ValueError(
                        f"Orchestrator token {token!r} missing from {surface.path}."
                    )
        else:
            for token in ("<feature-folder>/research/", "docs/research/"):
                if token not in text:
                    raise ValueError(
                        f"Research root token {token!r} missing from {surface.path}."
                    )


def find_extra_generated_targets(expected_paths: set[Path]) -> list[Path]:
    """Find marked generated files outside the exact target set."""

    roots = (Path(".codex/agents"), Path(".github"), Path(".claude"))
    extras: list[Path] = []
    for root in roots:
        for path in sorted((REPO_ROOT / root).rglob("*")):
            if not path.is_file() or path.suffix not in {".md", ".toml"}:
                continue
            relative_path = path.relative_to(REPO_ROOT)
            if relative_path in expected_paths:
                continue
            contents = path.read_text(encoding="utf-8", errors="replace")
            if GENERATED_MARKER in contents.partition("developer_instructions")[0]:
                extras.append(relative_path)
    return extras


def synchronize(*, check: bool) -> list[str]:
    """Write or verify every declared surface and reject extra generated files."""

    outputs = expected_outputs()
    errors: list[str] = []
    for path, expected in outputs.items():
        absolute_path = REPO_ROOT / path
        actual = (
            absolute_path.read_text(encoding="utf-8")
            if absolute_path.is_file()
            else None
        )
        if check:
            if actual is None:
                errors.append(
                    f"Generated orchestration surface is missing: {path.as_posix()}"
                )
            elif actual != expected:
                errors.append(
                    f"Generated orchestration surface is stale: {path.as_posix()}"
                )
        elif actual != expected:
            absolute_path.parent.mkdir(parents=True, exist_ok=True)
            absolute_path.write_text(expected, encoding="utf-8", newline="\n")
            print(f"UPDATED {path.as_posix()}")
    for extra in find_extra_generated_targets(set(outputs)):
        errors.append(f"Unexpected generated orchestration surface: {extra.as_posix()}")
    if not errors:
        print(f"VERIFIED {len(outputs)} orchestration customization surfaces")
    return errors


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report generated-surface drift without writing.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """Generate or check the exact orchestration customization surfaces."""

    args = build_parser().parse_args(argv)
    try:
        errors = synchronize(check=bool(args.check))
    except (FileNotFoundError, OSError, ValueError) as error:
        print(str(error), file=sys.stderr)
        return 1
    for error in errors:
        print(error, file=sys.stderr)
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
