<#
.SYNOPSIS
    Behavioral tests for the integration-cost scheduling layer (issue #722).

.DESCRIPTION
    Mirrors tests/scripts/dev_tools/test_blast_radius_scheduling.py against
    .claude/lib/blast-radius/BlastRadiusScheduling.psm1: the hard reason
    classes, every integer cost term (same_file, append_only with its precedence
    over same_file, possible_overlap, module, and the mergeable zero), the
    pairwise benefit with its default_band fallback, the integer inequality at
    its boundary, first-kind reason selection, the strict conflict_tolerance
    reader, the committed scheduling fixtures, strict identity over the existing
    contention corpus, pair ordering, and symmetry. Each It follows
    Arrange-Act-Assert. The tests read only committed fixture files, create no
    temporary file, and start no external process.

    The per-fixture and per-case It blocks are generated by discovery-time loops
    with the fixture or case name interpolated into the It name, so a Pester
    FullName filter on a fixture name selects the matching test.
#>

# Discovery-time corpus enumeration. Pester runs the file body during discovery,
# so every generated It needs its case data here.
$fixtureDirectory = (Resolve-Path "$PSScriptRoot/../../../../tests/fixtures/blast_radius").Path
$schedulingStem = @(
    'scheduling-452-shared-surface-hard',
    'scheduling-452-directory-prefix-weighted',
    'scheduling-452-negative-controls',
    'scheduling-soft-pair-tolerated',
    'scheduling-absent-key-strict'
)
$schedulingCase = @($schedulingStem | ForEach-Object {
        @{ FixtureName = $_; FixturePath = (Join-Path $fixtureDirectory "scheduling/$_.json") }
    })
$conflictCase = @(
    Get-ChildItem -Path $fixtureDirectory -Filter '*.json' -File |
        Sort-Object -Property Name |
            Where-Object { (Get-Content -Path $_.FullName -Raw | ConvertFrom-Json -AsHashtable)['input'].ContainsKey('radius_a') } |
                ForEach-Object { @{ FixtureName = $_.BaseName; FixturePath = $_.FullName } }
)
$readerCase = @(
    'non-object', 'percent-negative', 'percent-float', 'percent-string', 'percent-bool',
    'weight-zero', 'weight-bool', 'weight-float', 'weight-unknown-name', 'weight-missing-name',
    'band-duration-zero', 'band-missing-name', 'default-band-out-of-range', 'append-only-not-list'
)

BeforeAll {
    # The facade is imported first and the scheduling module second, because the
    # facade re-imports its siblings with -Force; the reverse order leaves the
    # scheduling-only exports unresolvable in this scope.
    $facadePath = (Resolve-Path "$PSScriptRoot/../../../../.claude/lib/blast-radius/BlastRadius.psm1").Path
    $schedulingPath = (Resolve-Path "$PSScriptRoot/../../../../.claude/lib/blast-radius/BlastRadiusScheduling.psm1").Path
    Import-Module $facadePath -Force
    Import-Module $schedulingPath -Force
    # The relation is passed explicitly to every scheduling call, so no call
    # depends on command resolution inside the scheduling module.
    $script:ConflictRelation = ${function:Test-BlastRadiusConflict}

    # The committed conflict_tolerance member (plan block B2), returned fresh so
    # a test may mutate its copy.
    function Get-CommittedToleranceMember {
        return @{
            tolerance_percent = 100
            weights           = @{ same_file = 8; possible_overlap = 2; append_only = 1; module = 2 }
            band_durations    = @{ C1 = 1; C2 = 2; C3 = 4; C4 = 8 }
            default_band      = 'C1'
            append_only_paths = @('**/CHANGELOG.md')
        }
    }

    # A minimal truth table carrying the committed member, with overrides.
    function Get-TestConfig {
        param([hashtable] $Override = @{})
        $member = Get-CommittedToleranceMember
        foreach ($key in $Override.Keys) { $member[$key] = $Override[$key] }
        return @{
            version               = 1
            shared_surfaces       = @()
            shared_surface_globs  = @()
            mergeable_paths       = @('**/*.csproj')
            conflict_tolerance    = $member
            modules               = @{ config = @('config/**') }
            over_breadth_fraction = 0.25
        }
    }

    # A declared radius whose unspecified levels are empty.
    function Get-TestRadius {
        param([string[]] $Paths = @(), [string[]] $Modules = @(), [string[]] $SharedSurfaces = @(), [string[]] $Contracts = @())
        return @{
            paths = $Paths; modules = $Modules; shared_surfaces = $SharedSurfaces; contracts = $Contracts
            source = 'declared'; computed_at = '2026-09-27T00-00'
        }
    }

    # Deep copy through JSON so a case can mutate its config without leaking.
    function Copy-TestValue {
        param([object] $Value)
        return (ConvertTo-Json -InputObject $Value -Depth 20 | ConvertFrom-Json -AsHashtable)
    }

    function Read-TestFixture {
        param([string] $Path)
        return (Get-Content -Path $Path -Raw | ConvertFrom-Json -AsHashtable)
    }

    # Canonical one-line forms, so edge lists compare independently of key order.
    function Format-TestEdge {
        param([object[]] $Edge)
        return @($Edge | ForEach-Object { '{0}-{1}|{2}|{3}|{4}|{5}' -f $_['a'], $_['b'], $_['reason'], $_['hard'], $_['cost'], $_['benefit'] })
    }
    function Format-TestTolerated {
        param([object[]] $Overlap)
        return @($Overlap | ForEach-Object { '{0}-{1}|{2}|{3}|{4}' -f $_['a'], $_['b'], (@($_['reasons']) -join ','), $_['cost'], $_['benefit'] })
    }

    # Build the named invalid conflict_tolerance member of the reader cases.
    function Get-InvalidToleranceMember {
        param([string] $Case)
        if ($Case -eq 'non-object') { return , @('tolerance_percent', 100) }
        $member = Get-CommittedToleranceMember
        switch ($Case) {
            'percent-negative' { $member['tolerance_percent'] = -1 }
            'percent-float' { $member['tolerance_percent'] = 1.5 }
            'percent-string' { $member['tolerance_percent'] = '100' }
            'percent-bool' { $member['tolerance_percent'] = $true }
            'weight-zero' { $member['weights']['same_file'] = 0 }
            'weight-bool' { $member['weights']['module'] = $true }
            'weight-float' { $member['weights']['append_only'] = 1.0 }
            'weight-unknown-name' { $member['weights']['same_symbol'] = 3 }
            'weight-missing-name' { $member['weights'].Remove('module') }
            'band-duration-zero' { $member['band_durations']['C1'] = 0 }
            'band-missing-name' { $member['band_durations'].Remove('C4') }
            'default-band-out-of-range' { $member['default_band'] = 'C5' }
            'append-only-not-list' { $member['append_only_paths'] = 'x.md' }
            default { throw "unknown reader case $Case" }
        }
        return $member
    }

    # Replace tolerance_percent when a fixture case gives one; null keeps the config.
    function Get-ConfigForCase {
        param([hashtable] $Config, [object] $TolerancePercent)
        $copy = Copy-TestValue -Value $Config
        if ($null -ne $TolerancePercent) { $copy['conflict_tolerance']['tolerance_percent'] = $TolerancePercent }
        return $copy
    }

    # Pester reads $conflictCase only during discovery, so the run phase lists
    # the contention corpus again for the symmetry case.
    $script:FixtureDirectory = (Resolve-Path "$PSScriptRoot/../../../../tests/fixtures/blast_radius").Path
}

Describe 'BlastRadiusScheduling' {
    Context 'Edge rule terms' {
        It 'keeps a shared-surface overlap hard at every tolerance' {
            $a = Get-TestRadius -Paths 'src/a.py' -SharedSurfaces 'poetry.lock'
            $b = Get-TestRadius -Paths 'src/b.py' -SharedSurfaces 'poetry.lock'
            foreach ($tolerance in @(0, 100, 1000000)) {
                $decision = Get-BlastRadiusPairDecision -RadiusA $a -RadiusB $b -Config (Get-TestConfig -Override @{ tolerance_percent = $tolerance }) -Relation $script:ConflictRelation
                $decision['hard'] | Should -BeTrue -Because "tolerance $tolerance keeps a shared surface hard"
                $decision['edge'] | Should -BeTrue -Because "tolerance $tolerance keeps a hard pair an edge"
            }
        }

        It 'treats a contract dependency as hard' {
            $a = Get-TestRadius -Paths 'src/a.py' -Contracts 'computeWidget'
            $b = Get-TestRadius -Paths 'src/b.py' -Contracts 'computeWidget'
            $decision = Get-BlastRadiusPairDecision -RadiusA $a -RadiusB $b -Config (Get-TestConfig -Override @{ tolerance_percent = 1000000 }) -Relation $script:ConflictRelation
            $decision['hard'] | Should -BeTrue
            $decision['edge'] | Should -BeTrue
            $decision['cost'] | Should -Be 0 -Because 'a contract dependency carries no cost term'
            $decision['reason'] | Should -BeExactly 'contract_dependency'
        }

        It 'costs equal concrete entries the same_file weight' {
            $config = Get-TestConfig
            $tolerance = Get-ConfigConflictTolerance -Config $config
            Get-BlastRadiusPairCost -RadiusA (Get-TestRadius -Paths 'src/app.py') -RadiusB (Get-TestRadius -Paths 'src/app.py') -Config $config -Tolerance $tolerance | Should -Be 8
        }

        It 'evaluates append_only before same_file' {
            $config = Get-TestConfig
            $tolerance = Get-ConfigConflictTolerance -Config $config
            Get-BlastRadiusPairCost -RadiusA (Get-TestRadius -Paths 'CHANGELOG.md') -RadiusB (Get-TestRadius -Paths 'CHANGELOG.md') -Config $config -Tolerance $tolerance | Should -Be 1
            Get-BlastRadiusPairCost -RadiusA (Get-TestRadius -Paths 'docs') -RadiusB (Get-TestRadius -Paths 'docs/CHANGELOG.md') -Config $config -Tolerance $tolerance | Should -Be 1
        }

        It 'costs a directory-prefix overlap the possible_overlap weight' {
            $config = Get-TestConfig
            $tolerance = Get-ConfigConflictTolerance -Config $config
            $directory = Get-TestRadius -Paths 'scripts/dev_tools'
            $fileInside = Get-TestRadius -Paths 'scripts/dev_tools/compute_blast_radius.py'
            $glob = Get-TestRadius -Paths 'scripts/dev_tools/**'
            Get-BlastRadiusPairCost -RadiusA $directory -RadiusB $fileInside -Config $config -Tolerance $tolerance | Should -Be 2
            Get-BlastRadiusPairCost -RadiusA $directory -RadiusB $glob -Config $config -Tolerance $tolerance | Should -Be 2
            Get-BlastRadiusPairCost -RadiusA $glob -RadiusB $fileInside -Config $config -Tolerance $tolerance | Should -Be 2
        }

        It 'adds the module weight per shared module' {
            $config = Get-TestConfig
            $tolerance = Get-ConfigConflictTolerance -Config $config
            $a = Get-TestRadius -Paths 'src/a.py' -Modules 'core', 'docs', 'tests'
            $b = Get-TestRadius -Paths 'src/b.py' -Modules 'core', 'docs'
            Get-BlastRadiusPairCost -RadiusA $a -RadiusB $b -Config $config -Tolerance $tolerance | Should -Be 4
        }

        It 'costs mergeable paths nothing' {
            $config = Get-TestConfig
            $tolerance = Get-ConfigConflictTolerance -Config $config
            Get-BlastRadiusPairCost -RadiusA (Get-TestRadius -Paths 'pkg/app.csproj') -RadiusB (Get-TestRadius -Paths 'pkg/app.csproj') -Config $config -Tolerance $tolerance | Should -Be 0
            Get-BlastRadiusPairCost -RadiusA (Get-TestRadius -Paths 'pkg/app.csproj', 'src/app.py') -RadiusB (Get-TestRadius -Paths 'pkg/app.csproj', 'src/app.py') -Config $config -Tolerance $tolerance | Should -Be 8
        }

        It 'uses the minimum band duration as the benefit' {
            $tolerance = Get-ConfigConflictTolerance -Config (Get-TestConfig)
            Get-BlastRadiusPairBenefit -BandA 'C2' -BandB 'C4' -Tolerance $tolerance | Should -Be 2
            Get-BlastRadiusPairBenefit -BandA 'C4' -BandB 'C3' -Tolerance $tolerance | Should -Be 4
            { Get-BlastRadiusPairBenefit -BandA 'C9' -BandB 'C1' -Tolerance $tolerance } | Should -Throw -ExpectedMessage '*band*'
        }

        It 'uses default_band for a missing band' {
            $tolerance = Get-ConfigConflictTolerance -Config (Get-TestConfig -Override @{ default_band = 'C3' })
            Get-BlastRadiusPairBenefit -BandA $null -BandB 'C4' -Tolerance $tolerance | Should -Be 4
            Get-BlastRadiusPairBenefit -BandA $null -BandB $null -Tolerance $tolerance | Should -Be 4
            Get-BlastRadiusPairBenefit -BandA 'C1' -BandB $null -Tolerance $tolerance | Should -Be 1
        }

        It 'applies the integer inequality strictly at its boundary' {
            $a = Get-TestRadius -Paths 'scripts/dev_tools'
            $b = Get-TestRadius -Paths 'scripts/dev_tools/x.py'
            $below = Get-BlastRadiusPairDecision -RadiusA $a -RadiusB $b -Config (Get-TestConfig -Override @{ tolerance_percent = 199 }) -Relation $script:ConflictRelation
            $at = Get-BlastRadiusPairDecision -RadiusA $a -RadiusB $b -Config (Get-TestConfig -Override @{ tolerance_percent = 200 }) -Relation $script:ConflictRelation
            @($below['cost'], $below['benefit']) | Should -Be @(2, 1)
            $below['edge'] | Should -BeTrue -Because '200 > 199 yields an edge'
            $at['edge'] | Should -BeFalse -Because '200 > 200 is false, so the pair is tolerated'
            $at['conflict'] | Should -BeTrue
            $at['hard'] | Should -BeFalse
        }

        It 'records the first canonical reason kind' {
            $config = Get-TestConfig
            $first = Get-BlastRadiusPairDecision -RadiusA (Get-TestRadius -Paths 'src/app.py' -Modules 'core') -RadiusB (Get-TestRadius -Paths 'src/app.py' -Modules 'core') -Config $config -Relation $script:ConflictRelation
            $second = Get-BlastRadiusPairDecision -RadiusA (Get-TestRadius -Modules 'core' -SharedSurfaces 'poetry.lock') -RadiusB (Get-TestRadius -Modules 'core' -SharedSurfaces 'poetry.lock') -Config $config -Relation $script:ConflictRelation
            @($first['reasons']) | Should -Be @('path_overlap', 'module_overlap')
            $first['reason'] | Should -BeExactly 'path_overlap'
            @($second['reasons']) | Should -Be @('module_overlap', 'shared_surface_overlap')
            $second['reason'] | Should -BeExactly 'module_overlap'
        }

        It 'reads an absent key as strict' {
            $config = Get-TestConfig
            $config.Remove('conflict_tolerance')
            $tolerance = Get-ConfigConflictTolerance -Config $config
            $tolerance['tolerance_percent'] | Should -Be 0
            @('same_file', 'possible_overlap', 'append_only', 'module' | ForEach-Object { $tolerance['weights'][$_] }) | Should -Be @(1, 1, 1, 1)
            @('C1', 'C2', 'C3', 'C4' | ForEach-Object { $tolerance['band_durations'][$_] }) | Should -Be @(1, 1, 1, 1)
            $tolerance['default_band'] | Should -BeExactly 'C1'
            @($tolerance['append_only_paths']).Count | Should -Be 0
        }
    }

    Context 'conflict_tolerance reader' {
        foreach ($case in $readerCase) {
            It "rejects $case" -ForEach @(@{ Case = $case }) {
                $config = Get-TestConfig
                $config['conflict_tolerance'] = Get-InvalidToleranceMember -Case $Case
                { Get-ConfigConflictTolerance -Config $config } | Should -Throw -ExpectedMessage '*conflict_tolerance*'
            }
        }
    }

    Context 'Scheduling fixtures' {
        foreach ($case in $schedulingCase) {
            It "reproduces the expected decisions for $($case['FixtureName'])" -ForEach @($case) {
                $fixture = Read-TestFixture -Path $FixturePath
                $item = @($fixture['items'] | ForEach-Object { @{ key = $_['key']; radius = $_['radius']; band = $_['band'] } })
                $index = 0
                foreach ($fixtureCase in $fixture['cases']) {
                    $result = Get-BlastRadiusConflictEdge -Item $item -Config (Get-ConfigForCase -Config $fixture['config'] -TolerancePercent $fixtureCase['tolerance_percent']) -Relation $script:ConflictRelation
                    Format-TestEdge -Edge @($result['edges']) | Should -Be (Format-TestEdge -Edge @($fixtureCase['expected_edges'])) -Because "$FixtureName case $index edges"
                    Format-TestTolerated -Overlap @($result['tolerated_overlaps']) | Should -Be (Format-TestTolerated -Overlap @($fixtureCase['expected_tolerated'])) -Because "$FixtureName case $index tolerated overlaps"
                    $index++
                }
            }
        }

        It 'embeds the radii in every #452 scheduling fixture' {
            foreach ($stem in @('scheduling-452-shared-surface-hard', 'scheduling-452-directory-prefix-weighted', 'scheduling-452-negative-controls')) {
                $raw = Get-Content -Path (Join-Path $script:FixtureDirectory "scheduling/$stem.json") -Raw
                $fixture = $raw | ConvertFrom-Json -AsHashtable
                @($fixture['tags']) | Should -Contain '#452-case' -Because $stem
                foreach ($entry in $fixture['items']) {
                    $entry['radius'] | Should -BeOfType [System.Collections.IDictionary] -Because "$stem embeds each radius"
                    # The relation validates the exact radius key set and throws on a malformed record.
                    { Test-BlastRadiusConflict -RadiusA $entry['radius'] -RadiusB $entry['radius'] -Config @{} } | Should -Not -Throw
                }
                (ConvertTo-Json -InputObject $fixture['items'] -Depth 20) | Should -Not -Match '\.json' -Because "$stem references no fixture file"
            }
        }
    }

    Context 'Strict identity' {
        foreach ($case in $conflictCase) {
            It "matches detection at tolerance 0 for $($case['FixtureName'])" -ForEach @($case) {
                $fixtureInput = (Read-TestFixture -Path $FixturePath)['input']
                $absent = Copy-TestValue -Value $fixtureInput['config']
                $absent.Remove('conflict_tolerance')
                $zero = Copy-TestValue -Value $absent
                $zero['conflict_tolerance'] = Get-CommittedToleranceMember
                $zero['conflict_tolerance']['tolerance_percent'] = 0
                $item = @(@{ key = 1; radius = $fixtureInput['radius_a'] }, @{ key = 2; radius = $fixtureInput['radius_b'] })
                $detected = (Test-BlastRadiusConflict -RadiusA $fixtureInput['radius_a'] -RadiusB $fixtureInput['radius_b'] -Config $absent)['conflict']
                $expected = if ($detected) { @('1-2') } else { @() }
                foreach ($config in @($absent, $zero)) {
                    $result = Get-BlastRadiusConflictEdge -Item $item -Config $config -Relation $script:ConflictRelation
                    @($result['edges'] | ForEach-Object { '{0}-{1}' -f $_['a'], $_['b'] }) | Should -Be $expected -Because $FixtureName
                    @($result['tolerated_overlaps']).Count | Should -Be 0 -Because $FixtureName
                }
            }
        }
    }

    Context 'Ordering and symmetry' {
        It 'sorts edges and tolerated overlaps by pair' {
            $shared = 'src/app.py'
            $item = @(
                @{ key = 9; radius = (Get-TestRadius -Paths $shared); band = 'C4' },
                @{ key = 3; radius = (Get-TestRadius -Paths $shared); band = 'C4' },
                @{ key = 5; radius = (Get-TestRadius -Paths 'CHANGELOG.md'); band = 'C4' },
                @{ key = 1; radius = (Get-TestRadius -Paths 'CHANGELOG.md'); band = 'C4' },
                @{ key = 7; radius = (Get-TestRadius -Paths $shared); band = 'C4' }
            )
            $result = Get-BlastRadiusConflictEdge -Item $item -Config (Get-TestConfig -Override @{ tolerance_percent = 50 }) -Relation $script:ConflictRelation
            @($result['edges'] | ForEach-Object { '{0}-{1}' -f $_['a'], $_['b'] }) | Should -Be @('3-7', '3-9', '7-9')
            @($result['tolerated_overlaps'] | ForEach-Object { '{0}-{1}' -f $_['a'], $_['b'] }) | Should -Be @('1-5')
            { Get-BlastRadiusConflictEdge -Item @($item[0], $item[0]) -Config (Get-TestConfig) -Relation $script:ConflictRelation } | Should -Throw -ExpectedMessage '*distinct*'
            { Get-BlastRadiusConflictEdge -Item @(@{ key = $true; radius = (Get-TestRadius) }) -Config (Get-TestConfig) -Relation $script:ConflictRelation } | Should -Throw -ExpectedMessage '*key*'
        }

        It 'decides (b, a) the same as (a, b)' {
            $fixturePath = @(Get-ChildItem -Path $script:FixtureDirectory -Filter 'conflict-*.json' -File | Sort-Object -Property Name)
            $fixturePath.Count | Should -BeGreaterOrEqual 10 -Because 'the existing contention corpus must be present'
            foreach ($file in $fixturePath) {
                $fixtureInput = (Read-TestFixture -Path $file.FullName)['input']
                $config = Copy-TestValue -Value $fixtureInput['config']
                $config['conflict_tolerance'] = Get-CommittedToleranceMember
                $forward = Get-BlastRadiusPairDecision -RadiusA $fixtureInput['radius_a'] -RadiusB $fixtureInput['radius_b'] -Config $config -BandA 'C2' -BandB 'C4' -Relation $script:ConflictRelation
                $reverse = Get-BlastRadiusPairDecision -RadiusA $fixtureInput['radius_b'] -RadiusB $fixtureInput['radius_a'] -Config $config -BandA 'C4' -BandB 'C2' -Relation $script:ConflictRelation
                foreach ($field in @('conflict', 'edge', 'hard', 'cost', 'benefit', 'reason')) {
                    $reverse[$field] | Should -Be $forward[$field] -Because "$($file.BaseName) field $field"
                }
                @($reverse['reasons']) | Should -Be @($forward['reasons']) -Because $file.BaseName
            }
        }

        It 'fails fast naming -Relation when the relation is omitted' {
            { Get-BlastRadiusPairDecision -RadiusA (Get-TestRadius) -RadiusB (Get-TestRadius) -Config (Get-TestConfig) } | Should -Throw -ExpectedMessage '*-Relation is required*BlastRadius.psm1*'
            { Get-BlastRadiusConflictEdge -Item @() -Config (Get-TestConfig) } | Should -Throw -ExpectedMessage '*-Relation is required*BlastRadius.psm1*'
        }

        It 'invokes the supplied relation rather than resolving a command' {
            # Two empty radii never conflict under Test-BlastRadiusConflict, so a
            # conflict here can only come from the supplied stub.
            $stub = { @{ conflict = $true; reasons = @(@{ kind = 'contract_dependency'; detail = 'stub' }) } }
            $decision = Get-BlastRadiusPairDecision -RadiusA (Get-TestRadius) -RadiusB (Get-TestRadius) -Config (Get-TestConfig) -Relation $stub
            $decision['conflict'] | Should -BeTrue
            $decision['hard'] | Should -BeTrue
            $decision['reason'] | Should -BeExactly 'contract_dependency'
        }
    }
}
