"""Collect lightweight PR context artifacts for extension-side execution.

This bundled script is invoked from the scaffold extension and writes
summary/appendix placeholders using destination-repository cwd targeting.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def write_text(path: Path, content: str) -> None:
    """Write UTF-8 text to a destination artifact path."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    """Parse command args and emit PR context artifacts."""
    parser = argparse.ArgumentParser(description="Collect PR context artifacts")
    parser.add_argument("--base", required=True, help="Base branch")
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("artifacts/pr_context.summary.txt"),
        help="Summary output artifact path",
    )
    parser.add_argument(
        "--appendix-out",
        type=Path,
        default=Path("artifacts/pr_context.appendix.txt"),
        help="Appendix output artifact path",
    )
    args = parser.parse_args(argv)

    try:
        write_text(
            args.out,
            "# PR Context Summary\n\n"
            f"Base branch: {args.base}\n"
            "Generated by extension-side bundled collector.\n",
        )
        write_text(
            args.appendix_out,
            "# PR Context Appendix\n\n" f"Base branch: {args.base}\n",
        )
        return 0
    except Exception as exc:  # noqa: BLE001 - CLI top-level error handling
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
